// AUTO-GENERATED by MidManStudio Pool Type Generator.
// DO NOT edit this file manually.
// Regenerate via: MidManStudio > Pool Type Generator
// Generated: 2026-04-29 08:29:17

namespace MidManStudio.Core.Pools
{
    /// <summary>Network object pool type IDs. AUTO-GENERATED — do not edit manually.</summary>
    public enum PoolableNetworkObjectType
    {
    }
}
