// PackagePoolProviderBootstrapper.cs
// Editor-only. Runs automatically after import via [InitializeOnLoad].
// 1. Creates default PoolTypeProvider assets for the utilities package.
// 2. Writes stub enum files so the package compiles before the user
//    runs the generator for the first time.
//
// The stub enums contain only the entries shipped by utilities and projectile system.
// After the user creates their own PoolTypeProviderSO and runs
// MidManStudio > Pool Type Generator, the stubs are overwritten with the full
// combined enum that includes their game entries.

#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEngine;
using MidManStudio.Core.Pools.Generator;

namespace MidManStudio.Core.Editor
{
    [InitializeOnLoad]
    internal static class PackagePoolProviderBootstrapper
    {
        private const string UtilitiesDir  = "Assets/MidManStudio/Utilities/PoolProviders";
        private const string GeneratedDir  = "Assets/MidManStudio/Generated";

        // Sentinel file — if it exists we've already bootstrapped this project
        private const string SentinelFile  = "Assets/MidManStudio/Generated/.bootstrapped";

        static PackagePoolProviderBootstrapper()
        {
            EditorApplication.delayCall += Bootstrap;
        }

        [MenuItem("MidManStudio/Internal/Recreate Default Pool Providers")]
        public static void Bootstrap()
        {
            bool changed = false;
            changed |= EnsureUtilitiesObjectProvider();
            changed |= EnsureUtilitiesParticleProvider();
            changed |= EnsureStubEnums();

            if (changed)
            {
                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();
                Debug.Log("[PoolProviderBootstrapper] Default assets and stub enums created.");
            }
        }

        // ── Provider assets ───────────────────────────────────────────────────

        private static bool EnsureUtilitiesObjectProvider()
        {
            const string path = UtilitiesDir + "/PoolTypeProvider_Utilities.asset";
            if (File.Exists(path)) return false;

            EnsureDir(UtilitiesDir);
            var so = ScriptableObject.CreateInstance<PoolTypeProviderSO>();
            so.packageId   = "com.midmanstudio.utilities";
            so.displayName = "MidMan Studio Utilities";
            so.priority    = 0;
            so.entries.Add(new PoolEntryDefinition
            {
                entryName      = "SpawnableAudio",
                comment        = "Pooled one-shot / looping audio source",
                explicitOffset = 0
            });
            so.entries.Add(new PoolEntryDefinition
            {
                entryName      = "Trail",
                comment        = "Pooled trail renderer object",
                explicitOffset = 1
            });

            AssetDatabase.CreateAsset(so, path);
            return true;
        }

        private static bool EnsureUtilitiesParticleProvider()
        {
            const string path = UtilitiesDir + "/ParticlePoolTypeProvider_Utilities.asset";
            if (File.Exists(path)) return false;

            EnsureDir(UtilitiesDir);
            var so = ScriptableObject.CreateInstance<ParticlePoolTypeProviderSO>();
            so.packageId   = "com.midmanstudio.utilities";
            so.displayName = "MidMan Studio Utilities";
            so.priority    = 0;
            // Utilities defines no particle types by default

            AssetDatabase.CreateAsset(so, path);
            return true;
        }

        // ── Stub enum files ───────────────────────────────────────────────────
        // Written once so the package compiles immediately after import.
        // The generator overwrites these when the user clicks Generate Now.

        private static bool EnsureStubEnums()
        {
            // If all three stubs already exist, nothing to do
            string objPath  = GeneratedDir + "/PoolableObjectType.cs";
            string partPath = GeneratedDir + "/PoolableParticleType.cs";
            string netPath  = GeneratedDir + "/PoolableNetworkObjectType.cs";

            if (File.Exists(objPath)  &&
                File.Exists(partPath) &&
                File.Exists(netPath)) return false;

            EnsureDir(GeneratedDir);

            if (!File.Exists(objPath))
                WriteStubObjectEnum(objPath);

            if (!File.Exists(partPath))
                WriteStubParticleEnum(partPath);

            if (!File.Exists(netPath))
                WriteStubNetworkEnum(netPath);

            return true;
        }

        private static void WriteStubObjectEnum(string path)
        {
            File.WriteAllText(path,
@"// AUTO-GENERATED by MidManStudio Pool Type Generator.
// This stub is written on first import so the package compiles immediately.
// Run  MidManStudio > Pool Type Generator  to regenerate with your own entries.

namespace MidManStudio.Core.Pools
{
    /// <summary>Object pool type IDs. AUTO-GENERATED — do not edit manually.</summary>
    public enum PoolableObjectType
    {
        // ── com.midmanstudio.utilities  (block 0–99)  ──────────────────────────
        SpawnableAudio = 0, // Pooled one-shot / looping audio source [pinned]
        Trail          = 1, // Pooled trail renderer object [pinned]

        // ── com.midmanstudio.projectilesystem  (block 100–199)  ───────────────
        Projectile_Visual2D = 100, // 2D projectile sprite visual [pinned]
        Projectile_Visual3D = 101, // 3D projectile visual [pinned]
        Projectile_Flipbook = 102, // Sprite-sheet flipbook for impact explosions [pinned]
    }
}
");
        }

        private static void WriteStubParticleEnum(string path)
        {
            File.WriteAllText(path,
@"// AUTO-GENERATED by MidManStudio Pool Type Generator.
// This stub is written on first import so the package compiles immediately.
// Run  MidManStudio > Pool Type Generator  to regenerate with your own entries.

namespace MidManStudio.Core.Pools
{
    /// <summary>Particle pool type IDs. AUTO-GENERATED — do not edit manually.</summary>
    public enum PoolableParticleType
    {
        // ── com.midmanstudio.projectilesystem  (block 0–99)  ──────────────────
        Projectile_Impact           = 0,  // Generic hit / impact particle [pinned]
        Projectile_Explosion_Small  = 1,  // Small explosion [pinned]
        Projectile_Explosion_Medium = 2,  // Medium explosion [pinned]
        Projectile_Explosion_Large  = 3,  // Large explosion [pinned]
        Projectile_Headshot         = 4,  // Headshot / critical hit particle [pinned]
        Projectile_Tracer           = 5,  // Tracer round particle [pinned]
    }
}
");
        }

        private static void WriteStubNetworkEnum(string path)
        {
            File.WriteAllText(path,
@"// AUTO-GENERATED by MidManStudio Pool Type Generator.
// This stub is written on first import so the package compiles immediately.
// Run  MidManStudio > Pool Type Generator  to regenerate with your own entries.

namespace MidManStudio.Core.Pools
{
    /// <summary>Network object pool type IDs. AUTO-GENERATED — do not edit manually.</summary>
    public enum PoolableNetworkObjectType
    {
        // ── com.midmanstudio.netcode  (block 0–99)  ───────────────────────────
        // (no entries defined by default)
        _Reserved = 0,
    }
}
");
        }

        private static void EnsureDir(string dir)
        {
            if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);
        }
    }
}
#endif
