// UIStateTypeGenerator.cs
// Reads all UIStateTypeProviderSO assets and writes UIStateId.cs.
// Values are powers of 2 (bit positions) supporting [Flags] multi-state.
// Open via: MidManStudio > Utilities > UI State Type Generator

#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;
using MidManStudio.Core.UIState.Generator;

namespace MidManStudio.Core.Editor.UIState
{
    public static class UIStateTypeGeneratorCore
    {
        private const string OutputPath =
            "packages/com.midmanstudio.utilities/Runtime/UIState/Generated/UIStateId.cs";
        private const string Namespace = "MidManStudio.Core.UIState";

        public static (bool success, List<string> errors, List<string> warnings) Generate()
        {
            var errors   = new List<string>();
            var warnings = new List<string>();

            var providers = Collect();
            if (!Validate(providers, errors, warnings))
                return (false, errors, warnings);

            var sorted = providers.OrderBy(p => p.priority).ThenBy(p => p.packageId).ToList();
            Write(sorted);
            AssetDatabase.Refresh();
            return (true, errors, warnings);
        }

        private static List<UIStateTypeProviderSO> Collect()
        {
            var list  = new List<UIStateTypeProviderSO>();
            var guids = AssetDatabase.FindAssets("t:UIStateTypeProviderSO");
            foreach (var g in guids)
            {
                var a = AssetDatabase.LoadAssetAtPath<UIStateTypeProviderSO>(
                    AssetDatabase.GUIDToAssetPath(g));
                if (a != null) list.Add(a);
            }
            return list;
        }

        private static bool Validate(List<UIStateTypeProviderSO> providers,
            List<string> errors, List<string> warnings)
        {
            // Duplicate packageIds
            foreach (var d in providers.GroupBy(p => p.packageId).Where(g => g.Count() > 1))
                errors.Add($"Duplicate packageId '{d.Key}'.");

            var allNames = providers
                .SelectMany(p => (p.states ?? new()).Select(s => (s.enumName, p.packageId)))
                .ToList();

            // Duplicate names
            foreach (var d in allNames.GroupBy(x => x.enumName).Where(g => g.Count() > 1))
                errors.Add($"Duplicate state name '{d.Key}'.");

            // Invalid identifiers
            foreach (var (name, pkg) in allNames)
            {
                if (string.IsNullOrWhiteSpace(name))
                { warnings.Add($"[{pkg}] Empty state name skipped."); continue; }
                if (!IsValidIdentifier(name))
                    errors.Add($"[{pkg}] '{name}' is not a valid C# identifier.");
            }

            // Bit overflow — [Flags] on int supports 31 user bits
            int total = allNames.Count(x => !string.IsNullOrWhiteSpace(x.enumName));
            if (total > 30)
                errors.Add($"Total states ({total}) exceeds 30 — [Flags] int only has 31 usable bits.");

            return errors.Count == 0;
        }

        private static void Write(List<UIStateTypeProviderSO> providers)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED by MidManStudio UI State Type Generator.");
            sb.AppendLine("// DO NOT edit manually.");
            sb.AppendLine("// Regenerate via: MidManStudio > Utilities > UI State Type Generator");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// UI state identifiers. Flags enum — combine with | for multi-state visibility.");
            sb.AppendLine("    /// AUTO-GENERATED — do not edit.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Flags]");
            sb.AppendLine("    public enum UIStateId");
            sb.AppendLine("    {");
            sb.AppendLine("        None = 0,");
            sb.AppendLine();

            int bitPosition = 0; // tracks which power of 2 we're on

            foreach (var p in providers)
            {
                sb.AppendLine($"        // ── {p.displayName}  [{p.packageId}]  priority={p.priority} ──");

                foreach (var s in (p.states ?? new())
                    .Where(s => !string.IsNullOrWhiteSpace(s.enumName)))
                {
                    long value = 1L << bitPosition;
                    string comment = string.IsNullOrWhiteSpace(s.comment)
                        ? $" // bit {bitPosition}"
                        : $" // {s.comment}  (bit {bitPosition})";
                    sb.AppendLine($"        {s.enumName} = {value},{comment}");
                    bitPosition++;
                }
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var dir = Path.GetDirectoryName(OutputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);
            File.WriteAllText(OutputPath, sb.ToString(), Encoding.UTF8);
            Debug.Log($"[UIStateTypeGenerator] Wrote → {OutputPath}");
        }

        private static bool IsValidIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name)) return false;
            if (!char.IsLetter(name[0]) && name[0] != '_') return false;
            foreach (var c in name) if (!char.IsLetterOrDigit(c) && c != '_') return false;
            return true;
        }
    }

    // ── Editor Window ─────────────────────────────────────────────────────────

    public class UIStateTypeGeneratorWindow : EditorWindow
    {
        private List<string> _errors   = new();
        private List<string> _warnings = new();
        private bool         _ranOnce;
        private bool         _lastSuccess;
        private Vector2      _scroll;

        [MenuItem("MidManStudio/Utilities/UI State Type Generator")]
        public static void Open()
        {
            var w = GetWindow<UIStateTypeGeneratorWindow>("UI State Type Generator");
            w.minSize = new Vector2(460, 300);
        }

        private void OnGUI()
        {
            EditorGUILayout.Space(8);
            EditorGUILayout.LabelField("MidManStudio — UI State Type Generator",
                EditorStyles.boldLabel);
            EditorGUILayout.LabelField(
                "Generates UIStateId [Flags] enum from UIStateTypeProviderSO assets.\n" +
                "Each state gets a unique power-of-2 bit value. Combine with | in inspector.",
                EditorStyles.wordWrappedMiniLabel);

            EditorGUILayout.Space(8);
            DrawProviders();
            EditorGUILayout.Space(8);

            var old = GUI.backgroundColor;
            GUI.backgroundColor = new Color(0.3f, 0.85f, 0.3f);
            if (GUILayout.Button("⚙  Generate Now", GUILayout.Height(36)))
            {
                var (ok, errs, warns) = UIStateTypeGeneratorCore.Generate();
                _lastSuccess = ok; _errors = errs; _warnings = warns; _ranOnce = true;
            }
            GUI.backgroundColor = old;

            if (!_ranOnce) return;
            EditorGUILayout.Space(6);
            if (_lastSuccess)
                EditorGUILayout.HelpBox("✓ Generation successful.", MessageType.Info);
            foreach (var w in _warnings) EditorGUILayout.HelpBox(w, MessageType.Warning);
            foreach (var e in _errors)   EditorGUILayout.HelpBox(e, MessageType.Error);
        }

        private void DrawProviders()
        {
            EditorGUILayout.LabelField("Discovered Providers", EditorStyles.boldLabel);
            var guids = AssetDatabase.FindAssets("t:UIStateTypeProviderSO");
            if (guids.Length == 0)
            {
                EditorGUILayout.HelpBox(
                    "No UIStateTypeProviderSO assets found.\n" +
                    "Create one via: MidManStudio > Utilities > UI State Type Provider",
                    MessageType.Info);
                return;
            }

            _scroll = EditorGUILayout.BeginScrollView(_scroll, GUILayout.MaxHeight(100));
            foreach (var g in guids)
            {
                var a = AssetDatabase.LoadAssetAtPath<UIStateTypeProviderSO>(
                    AssetDatabase.GUIDToAssetPath(g));
                if (a == null) continue;
                EditorGUILayout.BeginHorizontal(EditorStyles.helpBox);
                EditorGUILayout.LabelField(
                    $"[{a.priority:D3}]  {a.displayName}  ({a.packageId})  —  {a.StateCount} state(s)",
                    EditorStyles.miniLabel);
                if (GUILayout.Button("Select", GUILayout.Width(50)))
                    Selection.activeObject = a;
                EditorGUILayout.EndHorizontal();
            }
            EditorGUILayout.EndScrollView();
        }
    }
}
#endif
