// UIStateContextGenerator.cs
// Reads all UIStateContextProviderSO assets and writes one [Flags] enum file per context.
// Output path: Runtime/UIState/Generated/{ContextName}UIState.cs
// Open via: MidManStudio > Utilities > UI State Context Generator

#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;
using MidManStudio.Core.UIState.Generator;

namespace MidManStudio.Core.Editor.UIState
{
    public static class UIStateContextGeneratorCore
    {
        private const string OutputDir = "packages/com.midmanstudio.utilities/Runtime/UIState/Generated/";
        private const string Namespace = "MidManStudio.Core.UIState";

        public static (bool success, List<string> errors, List<string> warnings) Generate()
        {
            var errors   = new List<string>();
            var warnings = new List<string>();

            var providers = Collect();
            if (providers.Count == 0)
            {
                warnings.Add("No UIStateContextProviderSO assets found.");
                return (true, errors, warnings);
            }

            if (!Validate(providers, errors, warnings))
                return (false, errors, warnings);

            foreach (var p in providers)
                WriteContext(p, warnings);

            AssetDatabase.Refresh();
            return (true, errors, warnings);
        }

        private static List<UIStateContextProviderSO> Collect()
        {
            var list  = new List<UIStateContextProviderSO>();
            var guids = AssetDatabase.FindAssets("t:UIStateContextProviderSO");
            foreach (var g in guids)
            {
                var a = AssetDatabase.LoadAssetAtPath<UIStateContextProviderSO>(
                    AssetDatabase.GUIDToAssetPath(g));
                if (a != null) list.Add(a);
            }
            return list;
        }

        private static bool Validate(List<UIStateContextProviderSO> providers,
            List<string> errors, List<string> warnings)
        {
            // Duplicate context names
            foreach (var d in providers.GroupBy(p => p.contextName).Where(g => g.Count() > 1))
                errors.Add($"Duplicate contextName '{d.Key}'. Each context must have a unique name.");

            // Duplicate packageIds
            foreach (var d in providers.GroupBy(p => p.packageId).Where(g => g.Count() > 1))
                warnings.Add($"Multiple providers share packageId '{d.Key}'.");

            foreach (var p in providers)
            {
                if (!IsValidIdentifier(p.contextName))
                    errors.Add($"contextName '{p.contextName}' is not a valid C# identifier.");

                int stateCount = 0;
                foreach (var s in p.states ?? new())
                {
                    if (string.IsNullOrWhiteSpace(s.enumName))
                    { warnings.Add($"[{p.contextName}] Empty state name skipped."); continue; }

                    if (!IsValidIdentifier(s.enumName))
                        errors.Add($"[{p.contextName}] '{s.enumName}' is not a valid C# identifier.");

                    stateCount++;
                }

                if (stateCount > 30)
                    errors.Add($"[{p.contextName}] Has {stateCount} states — [Flags] int supports max 30.");
            }

            return errors.Count == 0;
        }

        private static void WriteContext(UIStateContextProviderSO p, List<string> warnings)
        {
            string enumName = $"{p.contextName}UIState";
            string filePath = Path.Combine(OutputDir, $"{enumName}.cs");

            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED by MidManStudio UI State Context Generator.");
            sb.AppendLine("// DO NOT edit manually.");
            sb.AppendLine("// Regenerate via: MidManStudio > Utilities > UI State Context Generator");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"// Context: {p.contextName}  Package: {p.packageId}");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// UI states for the {p.contextName} context.");
            sb.AppendLine($"    /// [Flags] — combine with | for multi-state visibility.");
            sb.AppendLine($"    /// AUTO-GENERATED — do not edit.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine("    [Flags]");
            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");
            sb.AppendLine("        None = 0,");
            sb.AppendLine();

            int bit = 0;
            foreach (var s in (p.states ?? new())
                .Where(s => !string.IsNullOrWhiteSpace(s.enumName)))
            {
                long val    = 1L << bit;
                string cmt  = string.IsNullOrWhiteSpace(s.comment)
                    ? $" // bit {bit}"
                    : $" // {s.comment}  (bit {bit})";
                sb.AppendLine($"        {s.enumName} = {val},{cmt}");
                bit++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            if (!Directory.Exists(OutputDir))
                Directory.CreateDirectory(OutputDir);

            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
            Debug.Log($"[UIStateContextGenerator] Wrote → {filePath}");
        }

        private static bool IsValidIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name)) return false;
            if (!char.IsLetter(name[0]) && name[0] != '_') return false;
            foreach (var c in name) if (!char.IsLetterOrDigit(c) && c != '_') return false;
            return true;
        }
    }

    // ── Editor Window ─────────────────────────────────────────────────────────

    public class UIStateContextGeneratorWindow : EditorWindow
    {
        private List<string> _errors   = new();
        private List<string> _warnings = new();
        private bool         _ranOnce;
        private bool         _lastSuccess;
        private Vector2      _scroll;

[MenuItem("MidManStudio/Utilities/UI State Context Generator",priority = 104)]
        public static void Open()
        {
            var w = GetWindow<UIStateContextGeneratorWindow>("UI State Generator");
            w.minSize = new Vector2(480, 340);
        }

        private void OnGUI()
        {
            EditorGUILayout.Space(8);
            EditorGUILayout.LabelField("MidManStudio — UI State Context Generator",
                EditorStyles.boldLabel);
            EditorGUILayout.LabelField(
                "Generates one [Flags] enum per UIStateContextProviderSO.\n" +
                "Create a MID_UIStateContext SO asset per context to use at runtime.",
                EditorStyles.wordWrappedMiniLabel);

            EditorGUILayout.Space(8);
            DrawProviders();
            EditorGUILayout.Space(8);

            var old = GUI.backgroundColor;
            GUI.backgroundColor = new Color(0.3f, 0.85f, 0.3f);
            if (GUILayout.Button("⚙  Generate Now", GUILayout.Height(36)))
            {
                var (ok, errs, warns) = UIStateContextGeneratorCore.Generate();
                _lastSuccess = ok; _errors = errs; _warnings = warns; _ranOnce = true;
            }
            GUI.backgroundColor = old;

            if (!_ranOnce) return;
            EditorGUILayout.Space(6);
            if (_lastSuccess)
                EditorGUILayout.HelpBox("✓ Generation successful.", MessageType.Info);
            foreach (var w in _warnings) EditorGUILayout.HelpBox(w, MessageType.Warning);
            foreach (var e in _errors)   EditorGUILayout.HelpBox(e, MessageType.Error);
        }

        private void DrawProviders()
        {
            EditorGUILayout.LabelField("Discovered Contexts", EditorStyles.boldLabel);
            var guids = AssetDatabase.FindAssets("t:UIStateContextProviderSO");
            if (guids.Length == 0)
            {
                EditorGUILayout.HelpBox(
                    "No UIStateContextProviderSO assets found.\n" +
                    "Create via: MidManStudio > Utilities > UI State Context Provider",
                    MessageType.Info);
                return;
            }

            _scroll = EditorGUILayout.BeginScrollView(_scroll, GUILayout.MaxHeight(120));
            foreach (var g in guids)
            {
                var a = AssetDatabase.LoadAssetAtPath<UIStateContextProviderSO>(
                    AssetDatabase.GUIDToAssetPath(g));
                if (a == null) continue;
                EditorGUILayout.BeginHorizontal(EditorStyles.helpBox);
                EditorGUILayout.LabelField(
                    $"{a.contextName}UIState  ({a.packageId})  —  {a.StateCount} state(s)",
                    EditorStyles.miniLabel);
                if (GUILayout.Button("Select", GUILayout.Width(50)))
                    Selection.activeObject = a;
                EditorGUILayout.EndHorizontal();
            }
            EditorGUILayout.EndScrollView();
        }
    }
}
#endif
