// AUTO-GENERATED by MidManStudio Library Type Generator.
// DO NOT edit manually.
// Regenerate via: MidManStudio > Utilities > Library Type Generator

namespace MidManStudio.Core.Libraries
{
    /// <summary>Library item keys. AUTO-GENERATED — do not edit.</summary>
    public enum LibraryItemId
    {
        // (no items defined — run the generator after adding providers)
        _Reserved = 0,
    }
}
