// AUTO-GENERATED by MidManStudio Pool Type Generator.
// DO NOT edit this file manually.
// Regenerate via: MidManStudio >  Utilities > Pool Type Generator
// Generated: 2026-05-13 09:22:53

namespace MidManStudio.Core.Pools
{
    /// <summary>Particle pool type IDs. AUTO-GENERATED — do not edit manually.</summary>
    public enum PoolableParticleType
    {
        // ── MidMan Studio Utilities  [com.midmanstudio.utilities]  (block 0–99)  priority=0  ──────────────────────────
        // (no entries defined)

        // ── MidMan Projectile System  [com.midmanstudio.projectilesystem]  (block 100–199)  priority=10  ──────────────────────────
        Projectile_Impact = 100, // Generic hit / impact particle [pinned]
        Projectile_Explosion_Small = 101, // Small explosion [pinned]
        Projectile_Explosion_Medium = 102, // Medium explosion [pinned]
        Projectile_Explosion_Large = 103, // Large explosion [pinned]
        Projectile_Headshot = 104, // Headshot / critical hit particle [pinned]
        Projectile_Tracer = 105, // Tracer round particle [pinned]
    }
}
