// AUTO-GENERATED by MidManStudio Pool Type Generator.
// DO NOT edit this file manually.
// Regenerate via: MidManStudio >  Utilities > Pool Type Generator
// Generated: 2026-05-12 17:45:32

namespace MidManStudio.Core.Pools
{
    /// <summary>Object pool type IDs. AUTO-GENERATED — do not edit manually.</summary>
    public enum PoolableObjectType
    {
        // ── MidMan Studio Utilities  [com.midmanstudio.utilities]  (block 0–99)  priority=0  ──────────────────────────
        SpawnableAudio = 0, // Pooled one-shot / looping audio source [pinned]
        Trail = 1, // Pooled trail renderer object [pinned]

        // ── MidMan Projectile System  [com.midmanstudio.projectilesystem]  (block 100–199)  priority=10  ──────────────────────────
        Projectile_Visual2D = 100, // 2D projectile sprite visual [pinned]
        Projectile_Visual3D = 101, // 3D projectile visual [pinned]
        Projectile_Flipbook = 102, // Sprite-sheet flipbook for impact explosions [pinned]
    }
}
