// AUTO-GENERATED by MidManStudio Pool Type Generator.
// DO NOT edit this file manually.
// Regenerate via: MidManStudio > Pool Type Generator
// Generated: 2026-04-29 08:29:17

namespace MidManStudio.Core.Pools
{
    /// <summary>Object pool type IDs. AUTO-GENERATED — do not edit manually.</summary>
    public enum PoolableObjectType
    {
        // ── MidMan Studio Utilities  [com.midmanstudio.utilities]  (block 0–99)  priority=0  ──────────────────────────
        SpawnableAudio = 0, // Pooled one-shot / looping audio source [pinned]
        Trail = 1, // Pooled trail renderer object [pinned]

        // ── My Game  [com.mygame]  (block 100–199)  priority=100  ──────────────────────────
        Mugen = 100, // Something cool
    }
}
