// AUTO-GENERATED by MidManStudio Pool Type Generator.
// DO NOT edit this file manually.
// Regenerate via: MidManStudio >  Utilities > Pool Type Generator
// Generated: 2026-05-12 17:45:32

namespace MidManStudio.Core.Pools
{
    /// <summary>Network object pool type IDs. AUTO-GENERATED — do not edit manually.</summary>
    public enum PoolableNetworkObjectType
    {
        // ── MidMan Studio Netcode  [com.midmanstudio.netcode]  (block 0–99)  priority=0  ──────────────────────────
        NetProjectileBlueprint = 0, // Networke projectile blueprint for managed projectile [pinned]
    }
}
