// AUTO-GENERATED by MidManStudio Pool Type Generator.
// DO NOT edit this file manually.
// Regenerate via: MidManStudio >  Utilities > Pool Type Generator
// Generated: 2026-05-13 09:22:53

namespace MidManStudio.Core.Pools
{
    /// <summary>Network object pool type IDs. AUTO-GENERATED — do not edit manually.</summary>
    public enum PoolableNetworkObjectType
    {
        // ── MidMan Studio Netcode  [com.midmanstudio.netcode]  (block 0–99)  priority=0  ──────────────────────────
        // (no entries defined)

        // ── MidMan Projectile System  [com.midmanstudio.projectilesystem]  (block 100–199)  priority=10  ──────────────────────────
        BaseProjectileBlueprint = 100, // Base Network Projectile Blueprint for Managed Projectiles [pinned]
    }
}
